// يولّد src/shared/fx/audio-credits.js من provenance المؤثرات والموسيقى وسجلّ المصادر: المصادر
// المرخَّصة (اسم، رابط، رخصة، عدد الملفات)، ومدخلات الإسناد الإلزامي (CC BY ونحوها) بسطر الاعتماد،
// وما بقي من تأليف ميدان. شاشة «عن ميدان» تعرضه، وCI يتحقق أنه مطابق (--check).
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const assetsDir = path.join(root, 'assets/audio/maydan-v3');
export const creditsFile = path.join(root, 'src/shared/fx/audio-credits.js');

export function buildCredits(cueProvenance, musicProvenance, registry) {
  const attribution = [], sources = new Map(), inHouse = { cues: [], tracks: [] };
  for (const [kind, items] of [['cues', cueProvenance.cues], ['tracks', musicProvenance.tracks]]) {
    for (const [id, info] of Object.entries(items)) {
      const s = info.source;
      if (!s) { inHouse[kind].push(id); continue; }
      const provider = registry.providers[s.provider] || {};
      if (s.attribution) attribution.push({ id: `${kind === 'cues' ? 'cue' : 'music'}:${id}`, title: s.title, author: s.author, sourceUrl: s.sourcePage, license: s.license, licenseUrl: s.licenseUrl, creditLine: s.creditLine || `${s.title} — ${s.author}` });
      const entry = sources.get(s.provider) || { provider: s.provider, name: provider.name || s.providerName, url: provider.url || s.sourcePage, license: s.license, licenseUrl: s.licenseUrl, attribution: !!s.attribution, items: 0, cues: [], tracks: [] };
      entry.items += 1; entry[kind].push(id); sources.set(s.provider, entry);
    }
  }
  return { attribution, sources: [...sources.values()].sort((a, b) => b.items - a.items || a.provider.localeCompare(b.provider)), inHouse };
}
export function renderCredits(credits) {
  return '// Generated by scripts/audio/credits.mjs from assets/audio/maydan-v3/{provenance,music/provenance,sources}.json — do not edit.\n'
    + '// Shown on the About screen (AudioCredits.jsx); entries under `attribution` are licenses that require a visible credit.\n'
    + `export const AUDIO_CREDITS = ${JSON.stringify(credits, null, 2)};\n`;
}
export async function generate() {
  const [cues, music, registry] = await Promise.all(['provenance.json', 'music/provenance.json', 'sources.json'].map(async (f) => JSON.parse(await readFile(path.join(assetsDir, f), 'utf8'))));
  return renderCredits(buildCredits(cues, music, registry));
}
async function main() {
  const text = await generate();
  if (process.argv.includes('--check')) {
    const current = await readFile(creditsFile, 'utf8').catch(() => '');
    if (current !== text) throw new Error('src/shared/fx/audio-credits.js is stale; run node scripts/audio/credits.mjs');
    console.log('Audio credits verified'); return;
  }
  await writeFile(creditsFile, text, 'utf8');
  console.log(`wrote ${path.relative(root, creditsFile)}`);
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(error.stack || error.message); process.exit(1); });
