// Generated by scripts/audio/credits.mjs from assets/audio/maydan-v3/{provenance,music/provenance,sources}.json — do not edit.
// Shown on the About screen (AudioCredits.jsx); entries under `attribution` are licenses that require a visible credit.
export const AUDIO_CREDITS = {
  "attribution": [],
  "sources": [
    {
      "provider": "dustyroom",
      "name": "Dustyroom — Free Casual Game Sounds",
      "url": "https://dustyroom.com/free-casual-game-sounds/",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "attribution": false,
      "items": 6,
      "cues": [
        "pop",
        "correct",
        "wrong",
        "buzzer",
        "timeout",
        "whoosh"
      ],
      "tracks": []
    },
    {
      "provider": "mixkit-sfx",
      "name": "Mixkit Sound Effects (Envato)",
      "url": "https://mixkit.co/free-sound-effects/",
      "license": "Mixkit Sound Effects Free License",
      "licenseUrl": "https://mixkit.co/license/#sfx",
      "attribution": false,
      "items": 1,
      "cues": [
        "explosion"
      ],
      "tracks": []
    }
  ],
  "inHouse": {
    "cues": [
      "click",
      "tick",
      "tickFast",
      "countdown",
      "start",
      "reveal",
      "win",
      "drumroll",
      "pass"
    ],
    "tracks": [
      "home",
      "calm",
      "tense",
      "finale"
    ]
  }
};
