// Generated by scripts/audio/music.mjs — Maydan's background music (in-house compositions and licensed tracks; see assets/audio/maydan-v3/music/provenance.json).
// Masters: assets/audio/maydan-v3/music/*.wav; files: public/audio/music (AAC 192 kb/s, content-hashed names), fetched on first play, never precached.
export const MUSIC_BANK = {
  "home": {
    "url": "audio/music/home-ee5839.m4a",
    "seconds": 45.7143,
    "frames": 2194285,
    "bytes": 1149498,
    "sha256": "ee58395dd3992e877d009bbae1920d3d11c4b98ab9c08986e3a7387e128544e7",
    "masterSha256": "a04f3c2ee19939386706181149fa230c7522bee5a87fb5e0f289feadee4dc943",
    "loop": true,
    "bpm": 84
  },
  "calm": {
    "url": "audio/music/calm-cdad51.m4a",
    "seconds": 58.1818,
    "frames": 2792728,
    "bytes": 1420805,
    "sha256": "cdad511aeba2c8a9f591c1591a69fce18404053309cbad5f5cdd05e9f3c11389",
    "masterSha256": "0b6cb624d3449eace2742d3b11538890d3ff743a9c5b3ad7ec453a62afe36efa",
    "loop": true,
    "bpm": 66
  },
  "tense": {
    "url": "audio/music/tense-87ace7.m4a",
    "seconds": 38.4,
    "frames": 1843200,
    "bytes": 967875,
    "sha256": "87ace7a2615a718695aca1780778b57b69e5b44d3e230de4a5eabe7501b66a60",
    "masterSha256": "2d7b5f75db59d03d5c81256e52e8c6ca456b3c28a9b4260930b4d70166ca9c71",
    "loop": true,
    "bpm": 100
  },
  "finale": {
    "url": "audio/music/finale-f3b09a.m4a",
    "seconds": 6.5,
    "frames": 312000,
    "bytes": 144151,
    "sha256": "f3b09aaace534a2166d065ed001acefa9fc485f5c1f87ad8d6134fdbb5787995",
    "masterSha256": "22f64d309a134ccc114bb5f1bc92c1ed32530b6be9116eb1eb079af58f7062dc",
    "loop": false,
    "bpm": 96
  }
};
