// Generated by scripts/audio/music.mjs — Maydan's own background music (composed and synthesized in-repo).
// Masters: assets/audio/maydan-v2/music/*.wav; files: public/audio/music (AAC 192 kb/s), fetched on first play, never precached.
export const MUSIC_BANK = {
  "home": {
    "url": "audio/music/home.m4a",
    "seconds": 53.3333,
    "frames": 2560000,
    "bytes": 1336152,
    "sha256": "3d8a2323a571d7ff65d2b014be52dd6d750cf2b5655b0777f85adadd8f8cd576",
    "masterSha256": "58a3c120c7607f3226e4b69bccbd66f5c5cdaf5d30bfc513579187d78d90f876",
    "loop": true,
    "bpm": 72
  },
  "calm": {
    "url": "audio/music/calm.m4a",
    "seconds": 58.1818,
    "frames": 2792728,
    "bytes": 1443304,
    "sha256": "6185c0efb1f993ca3f6c0cc0f41b7f85249faaf416dfae0cadfebe34bb878f03",
    "masterSha256": "b7c98a8d9f18d9c3b75d94290c139216820d9bfa52a647a65a90eceed5cd4882",
    "loop": true,
    "bpm": 66
  },
  "tense": {
    "url": "audio/music/tense.m4a",
    "seconds": 40,
    "frames": 1920000,
    "bytes": 1014784,
    "sha256": "be60ce794581530c4599beb9902ce7031df544bcb59e3553e995f29f9f2a8f0c",
    "masterSha256": "5eeb9189a11f76be433f3f1cf6575805d0439f242651957331fd03c20c830c6b",
    "loop": true,
    "bpm": 96
  },
  "finale": {
    "url": "audio/music/finale.m4a",
    "seconds": 6.5,
    "frames": 312000,
    "bytes": 165974,
    "sha256": "579d07a3a25c53c36804906f47878fb6603ff4d27a0a9c7a75e613d497c7041b",
    "masterSha256": "ba4009e80d19be9eeef1eb3d6c2ef55743df39bee96e60f3cb7ebd9f1efcca6f",
    "loop": false,
    "bpm": 84
  }
};
