// Generated by scripts/audio-bank.mjs from approved option A (+6 dB clicks).
// Original samples: Dustyroom and Chequered Ink. See assets/audio/maydan-casual/licenses/.
// The files live in public/audio (AAC 96 kb/s); sha256 covers the encoded file and
// masterSha256 the 24-bit PCM it was encoded from.
export const SAMPLE_RATE = 48000;
export const SAMPLE_BANK = {
  "tap": {
    "url": "audio/tap.m4a",
    "frames": 10338,
    "bytes": 3252,
    "sha256": "51b3bd13b6bce5c797698c435e25a1ac0c940b4b81490b1d8e87f5f80b83d234",
    "masterSha256": "769c826435c069a1d1c0b3788d5b36d7d92eb3ccd7f9bf0aa884154552cbddb2"
  },
  "correct": {
    "url": "audio/correct.m4a",
    "frames": 23993,
    "bytes": 7797,
    "sha256": "c3f0e0f5bec1f7b0c790c39d4606b3bdb60bd5410779c7345d750b77aa0025ee",
    "masterSha256": "611e1cd6629471560cd684b4a66f8afdc37f7f7a39c9f8d8c98e077c67477517"
  },
  "wrong": {
    "url": "audio/wrong.m4a",
    "frames": 8563,
    "bytes": 2853,
    "sha256": "68045730de77f8a288c59d90353fcc0d79cba9e74a583b1235ba8f625169f9cd",
    "masterSha256": "e5976a081465b6fbe07a08644c23718dfeece9d8046ab4638c59d02934cc1e2d"
  },
  "reveal": {
    "url": "audio/reveal.m4a",
    "frames": 74468,
    "bytes": 20096,
    "sha256": "a855995d020b1536af6492a14487b05be30c32a877ce2ff2bb13b6d8023c29fc",
    "masterSha256": "2240e91c441551d9a35b5eb76c7b85a4d9418ac68bbcfabef26440b973f30a9e"
  },
  "start": {
    "url": "audio/start.m4a",
    "frames": 100771,
    "bytes": 27327,
    "sha256": "eea808eed77fd7f51d016c1197f0283a883b29b172a5296a29280d7cc4b61040",
    "masterSha256": "52aea40bd0a982365448983302d752dd948e4dd8d0972bbbca38dbc5759d3dcc"
  },
  "win": {
    "url": "audio/win.m4a",
    "frames": 148888,
    "bytes": 37972,
    "sha256": "029d38278fee4cae926963c41f516dc2579d0d8341745f97da04157a923965dc",
    "masterSha256": "211b1ef945624e4d089b16ddf9447dfc5d29c2ba0879d5690ad88551545e5013"
  }
};
