// Generated by scripts/audio/build.mjs — Maydan's cue bank (in-house synthesis and licensed samples; see assets/audio/maydan-v3/provenance.json).
// Masters: assets/audio/maydan-v3/*.wav (48 kHz stereo PCM24); files: public/audio (AAC 160 kb/s), named after their content hash.
// sha256 covers the encoded file and masterSha256 the PCM master it was encoded from.
export const SAMPLE_RATE = 48000;
export const SAMPLE_BANK = {
  "click": {
    "url": "audio/click-6fa408.m4a",
    "frames": 12000,
    "bytes": 6530,
    "sha256": "6fa40842c402fa9bd911ad76283b0908b54c53fa207cc5708bf0c4f441a85ac1",
    "masterSha256": "775fa4e7ad25c687b1a9c89c6975a79b670e9f1e575a446393435b94f4b7a829"
  },
  "pop": {
    "url": "audio/pop-abb9bf.m4a",
    "frames": 10444,
    "bytes": 5439,
    "sha256": "abb9bf2066311ccce1096357b981e947f48997163e2eda5574a5ad099e3ff83f",
    "masterSha256": "69c6e539daffa44c5c460784609853bbac17ba9f47bdf6d5fa3fd8b049600af6"
  },
  "tick": {
    "url": "audio/tick-844a01.m4a",
    "frames": 4320,
    "bytes": 2450,
    "sha256": "844a01b1a023768b32fd7841fb510b9e6867d6d14d062a8fe51d8e00dd24779e",
    "masterSha256": "4c200fa0a8b131b1a711a8736ea20136716f9d44ffd3b00cf6f206ec96950677"
  },
  "tickFast": {
    "url": "audio/tick-fast-db1a19.m4a",
    "frames": 4320,
    "bytes": 2743,
    "sha256": "db1a19359ab22a7d1823e28c2fcc9f3496ee864deaaf7002657764a0f5be98d9",
    "masterSha256": "04c4a5756a42b47c4cf6be50976a0981db0ea9c2613f4a91d4df514b795e16e4"
  },
  "countdown": {
    "url": "audio/countdown-b231c6.m4a",
    "frames": 28800,
    "bytes": 13722,
    "sha256": "b231c6b09d64cf81b9a4af057edb39ff17aae8ec43f28f0fde165182c056df73",
    "masterSha256": "cb519278724c38473f0b8502747f08d3826fa40c4874deb7c9883a139e434ec6"
  },
  "start": {
    "url": "audio/start-765ccc.m4a",
    "frames": 72000,
    "bytes": 31356,
    "sha256": "765cccb92dfa832a79bb08350730b0499dd5572d06dd17dc76fd3653941283ee",
    "masterSha256": "d4883adcc1b2affab491d66bcb6ef46bdffe260a83a0523b1cf9ee0488d5e8f0"
  },
  "correct": {
    "url": "audio/correct-4958a5.m4a",
    "frames": 14486,
    "bytes": 7425,
    "sha256": "4958a5292906d25481e551b0ad0cae3568d4657c845e254cd4b3a6688d19f220",
    "masterSha256": "b4a6142ce1ee4aa8635a0b6596b1b82103d43983b53937a8069aff350f622d47"
  },
  "wrong": {
    "url": "audio/wrong-1a1155.m4a",
    "frames": 10338,
    "bytes": 4014,
    "sha256": "1a11550c094069043ffa6ae7051ebfd427dd557576e8fcef62a9df955f5cedc7",
    "masterSha256": "69ceacffcacefa3aeb8a9a81a0040210c0605438b0897375a291e6688dcefa79"
  },
  "buzzer": {
    "url": "audio/buzzer-7bed47.m4a",
    "frames": 19212,
    "bytes": 9521,
    "sha256": "7bed47fec0de2a9722ae44344755fc5a108a5fc25a031c069a78e1d2de02f002",
    "masterSha256": "b6dc0e8d7a75944e704e1a493f1fa14f7b3973f400248146fe8b9883c804008a"
  },
  "timeout": {
    "url": "audio/timeout-5881fd.m4a",
    "frames": 74174,
    "bytes": 32484,
    "sha256": "5881fd9254a4342ceee9a6fb0f77c1178be076b3c8fd30e1c0fca7c9a567bcf7",
    "masterSha256": "8ddbec0f412a5c3e47ee5cb63085f506e98575132c609ca75adca5fc58c06840"
  },
  "whoosh": {
    "url": "audio/whoosh-8ba94f.m4a",
    "frames": 40509,
    "bytes": 19281,
    "sha256": "8ba94fa52d50b9a79444c85394359b824d97dc38537e44d28fab20b83f80b9a7",
    "masterSha256": "414f96e5009fb0283c0357d79e2b7ab9781d97ace4cb7ef971a4a11c5380a44b"
  },
  "reveal": {
    "url": "audio/reveal-5701b5.m4a",
    "frames": 91200,
    "bytes": 38903,
    "sha256": "5701b5058f93e9cc918e9c3f593267bb2664cfaed3834d668a78cd66955a6b3c",
    "masterSha256": "c2eb18ca142148d395965a19ca04074d81549c74c974119e25708e3e5bbfebc4"
  },
  "win": {
    "url": "audio/win-77749b.m4a",
    "frames": 153600,
    "bytes": 66223,
    "sha256": "77749bc29a38dd93520a82e0541bf24c3d7dd7c2d19f5c07201b0f7118d28c74",
    "masterSha256": "aeac83dd4a6600529327f9ee8b4d170c36e1660bb7b89ed7821df19fd1302a6a"
  },
  "explosion": {
    "url": "audio/explosion-5c7ad4.m4a",
    "frames": 63936,
    "bytes": 27044,
    "sha256": "5c7ad4a53cb4473d12f8718a2ccf1c81d639dfa77ced70b70995758c4798750c",
    "masterSha256": "0f848c8e588009ea38a6d4222fd04f54455d55d1242c02ef79425b3be1bdd43a"
  },
  "drumroll": {
    "url": "audio/drumroll-b68a56.m4a",
    "frames": 81600,
    "bytes": 36222,
    "sha256": "b68a563b92fa85549b4156214dd6e50e4cff0be8920086609e0dd37508d658a5",
    "masterSha256": "479f0f36eab232ca72047007ec5bd3148f96d6b13fe9844c9ac6805379fe75bb"
  },
  "pass": {
    "url": "audio/pass-7a14c1.m4a",
    "frames": 21600,
    "bytes": 10323,
    "sha256": "7a14c1057131757a6be204123e3b06f3d74bb8eb6ac66e51f600ff9dd7506327",
    "masterSha256": "1480ddedcc98053fa5816b7bb563026b9d0fac020767612b1ca988253237706f"
  }
};
