// Generated by scripts/audio/build.mjs — Maydan's own synthesized cue bank (no third-party samples).
// Masters: assets/audio/maydan-v2/*.wav (48 kHz stereo PCM24); files: public/audio (AAC 160 kb/s).
// sha256 covers the encoded file and masterSha256 the PCM master it was encoded from.
export const SAMPLE_RATE = 48000;
export const SAMPLE_BANK = {
  "click": {
    "url": "audio/click.m4a",
    "frames": 12000,
    "bytes": 6530,
    "sha256": "6fa40842c402fa9bd911ad76283b0908b54c53fa207cc5708bf0c4f441a85ac1",
    "masterSha256": "775fa4e7ad25c687b1a9c89c6975a79b670e9f1e575a446393435b94f4b7a829"
  },
  "pop": {
    "url": "audio/pop.m4a",
    "frames": 24000,
    "bytes": 11506,
    "sha256": "60bd4d856574ebf15de7fcb5770bae4545c738706f48fccc8714c8ee4c7070f1",
    "masterSha256": "e55e6fdd4ebee41bff316d3535adcf339f7987936aad7c5c6e0e23cf23b1070f"
  },
  "tick": {
    "url": "audio/tick.m4a",
    "frames": 4320,
    "bytes": 2450,
    "sha256": "844a01b1a023768b32fd7841fb510b9e6867d6d14d062a8fe51d8e00dd24779e",
    "masterSha256": "4c200fa0a8b131b1a711a8736ea20136716f9d44ffd3b00cf6f206ec96950677"
  },
  "tickFast": {
    "url": "audio/tick-fast.m4a",
    "frames": 4320,
    "bytes": 2743,
    "sha256": "db1a19359ab22a7d1823e28c2fcc9f3496ee864deaaf7002657764a0f5be98d9",
    "masterSha256": "04c4a5756a42b47c4cf6be50976a0981db0ea9c2613f4a91d4df514b795e16e4"
  },
  "countdown": {
    "url": "audio/countdown.m4a",
    "frames": 28800,
    "bytes": 13722,
    "sha256": "b231c6b09d64cf81b9a4af057edb39ff17aae8ec43f28f0fde165182c056df73",
    "masterSha256": "cb519278724c38473f0b8502747f08d3826fa40c4874deb7c9883a139e434ec6"
  },
  "start": {
    "url": "audio/start.m4a",
    "frames": 72000,
    "bytes": 31356,
    "sha256": "765cccb92dfa832a79bb08350730b0499dd5572d06dd17dc76fd3653941283ee",
    "masterSha256": "d4883adcc1b2affab491d66bcb6ef46bdffe260a83a0523b1cf9ee0488d5e8f0"
  },
  "correct": {
    "url": "audio/correct.m4a",
    "frames": 43200,
    "bytes": 19664,
    "sha256": "d207bbe4ff6e8c6bdb1304ceb7b3530fd4a690bffda930e081f33f7d94b44041",
    "masterSha256": "342e797a5186e804c094b7b5ad6eea9fa17d4cc27dd66e6f4d06409e442056ee"
  },
  "wrong": {
    "url": "audio/wrong.m4a",
    "frames": 36000,
    "bytes": 16873,
    "sha256": "a5aef0a0999597d796630b1406a61bcda944902cf7b5109818b511db7aa4a47a",
    "masterSha256": "81288d17563b46c5032ea2ca046a2d3e897259087c62b42dffa5d105fdadc4a6"
  },
  "buzzer": {
    "url": "audio/buzzer.m4a",
    "frames": 38400,
    "bytes": 17577,
    "sha256": "368950a7c0b53b34cc08a2085b8b1619f1d4bd9e14c1f5e89552f8aa9c591a22",
    "masterSha256": "3483fd0f62fa728619874d84b12d97e8b7b4447f1925ee4dffbdf0ea7ac0dcf6"
  },
  "timeout": {
    "url": "audio/timeout.m4a",
    "frames": 62400,
    "bytes": 27199,
    "sha256": "d935a44c5f23e7bedfb0953a1164e2b9d7d62b6df72c8fdf89f6eab1599eb9e8",
    "masterSha256": "138e7aaf1304b38692e2cd8ae7a7e621f963815050bb1479aa1b47719d4dddb5"
  },
  "whoosh": {
    "url": "audio/whoosh.m4a",
    "frames": 26400,
    "bytes": 11849,
    "sha256": "bab4304eec87d99fac99735c0bc50f295a50920727e5e1f9d39cd6b93d1b9db7",
    "masterSha256": "f8400361529c05732a8683d6218db9655a82864eff291d7b0723adf75e50cb91"
  },
  "reveal": {
    "url": "audio/reveal.m4a",
    "frames": 91200,
    "bytes": 38903,
    "sha256": "5701b5058f93e9cc918e9c3f593267bb2664cfaed3834d668a78cd66955a6b3c",
    "masterSha256": "c2eb18ca142148d395965a19ca04074d81549c74c974119e25708e3e5bbfebc4"
  },
  "win": {
    "url": "audio/win.m4a",
    "frames": 153600,
    "bytes": 66223,
    "sha256": "77749bc29a38dd93520a82e0541bf24c3d7dd7c2d19f5c07201b0f7118d28c74",
    "masterSha256": "aeac83dd4a6600529327f9ee8b4d170c36e1660bb7b89ed7821df19fd1302a6a"
  },
  "explosion": {
    "url": "audio/explosion.m4a",
    "frames": 76800,
    "bytes": 33603,
    "sha256": "e6feda126ac021a8a0cd11b1fcd1b34639cea9bef0d7c0ba1c10f5b7896850d9",
    "masterSha256": "8ba4be79b37c2b0b7b29bb50de0165706ef352d12960417390ec1bed9b362546"
  },
  "drumroll": {
    "url": "audio/drumroll.m4a",
    "frames": 81600,
    "bytes": 36222,
    "sha256": "b68a563b92fa85549b4156214dd6e50e4cff0be8920086609e0dd37508d658a5",
    "masterSha256": "479f0f36eab232ca72047007ec5bd3148f96d6b13fe9844c9ac6805379fe75bb"
  },
  "pass": {
    "url": "audio/pass.m4a",
    "frames": 21600,
    "bytes": 10323,
    "sha256": "7a14c1057131757a6be204123e3b06f3d74bb8eb6ac66e51f600ff9dd7506327",
    "masterSha256": "1480ddedcc98053fa5816b7bb563026b9d0fac020767612b1ca988253237706f"
  }
};
