// Pack the approved 24-bit masters into the single-file game. No runtime fetch
// or codec decode: the first gesture can play offline and inside the iOS shell.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createHash } from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ids = ['tap', 'correct', 'wrong', 'reveal', 'start', 'win'];
const bank = {};
for (const id of ids) {
  const wav = await readFile(path.join(root, 'assets/audio/maydan-casual', `${id}.wav`));
  if (wav.toString('ascii', 0, 4) !== 'RIFF' || wav.toString('ascii', 8, 12) !== 'WAVE') throw new Error(`Not a WAV: ${id}`);
  let format, data;
  for (let pos = 12; pos + 8 <= wav.length;) {
    const name = wav.toString('ascii', pos, pos + 4), size = wav.readUInt32LE(pos + 4);
    const chunk = wav.subarray(pos + 8, pos + 8 + size);
    if (chunk.length !== size) throw new Error(`Truncated WAV: ${id}`);
    if (name === 'fmt ') format = chunk;
    if (name === 'data') data = chunk;
    pos += 8 + size + (size % 2);
  }
  if (!format || !data || format.readUInt16LE(0) !== 1 || format.readUInt16LE(2) !== 2
    || format.readUInt32LE(4) !== 48000 || format.readUInt16LE(14) !== 24 || data.length % 6) {
    throw new Error(`Expected stereo 48 kHz PCM24: ${id}`);
  }
  bank[id] = { frames: data.length / 6, sha256: createHash('sha256').update(data).digest('hex'), pcm: data.toString('base64') };
}
const target = path.join(root, 'src/shared/fx/sample-bank.js');
const text = '// Generated by scripts/audio-bank.mjs from approved option A (+6 dB clicks).\n'
  + '// Original samples: Dustyroom and Chequered Ink. See assets/audio/maydan-casual/licenses/.\n'
  + `export const SAMPLE_RATE = 48000;\nexport const SAMPLE_BANK = ${JSON.stringify(bank, null, 2)};\n`;
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== text) throw new Error('Audio bank differs from approved masters; run node scripts/audio-bank.mjs');
} else await writeFile(target, text, 'utf8');
console.log(`Audio bank: ${ids.length} approved cues, ${(Buffer.byteLength(text) / 1024).toFixed(1)} KB embedded`);
