// Encode the approved 24-bit masters into small AAC files under public/audio and
// write the manifest the sound bus reads. The cues are fetched once (the service
// worker precaches them for offline play and the iOS shell bundles dist/), then
// decoded with decodeAudioData on the first gesture. Shipping them as raw PCM
// inside index.html cost 2.8 MB of base64 on every cold start for 7.6 s of audio.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createHash } from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ids = ['tap', 'correct', 'wrong', 'reveal', 'start', 'win'];
const outDir = path.join(root, 'public/audio');
const target = path.join(root, 'src/shared/fx/sample-bank.js');
const check = process.argv.includes('--check');
const ffmpeg = createRequire(import.meta.url)('ffmpeg-static');

function wavInfo(wav, id) {
  if (wav.toString('ascii', 0, 4) !== 'RIFF' || wav.toString('ascii', 8, 12) !== 'WAVE') throw new Error(`Not a WAV: ${id}`);
  let format, data;
  for (let pos = 12; pos + 8 <= wav.length;) {
    const name = wav.toString('ascii', pos, pos + 4), size = wav.readUInt32LE(pos + 4);
    const chunk = wav.subarray(pos + 8, pos + 8 + size);
    if (chunk.length !== size) throw new Error(`Truncated WAV: ${id}`);
    if (name === 'fmt ') format = chunk;
    if (name === 'data') data = chunk;
    pos += 8 + size + (size % 2);
  }
  if (!format || !data || format.readUInt16LE(0) !== 1 || format.readUInt16LE(2) !== 2
    || format.readUInt32LE(4) !== 48000 || format.readUInt16LE(14) !== 24 || data.length % 6) {
    throw new Error(`Expected stereo 48 kHz PCM24: ${id}`);
  }
  return { frames: data.length / 6, masterSha256: createHash('sha256').update(data).digest('hex') };
}

const bank = {};
await mkdir(outDir, { recursive: true });
for (const id of ids) {
  const wavPath = path.join(root, 'assets/audio/maydan-casual', `${id}.wav`);
  const info = wavInfo(await readFile(wavPath), id);
  const file = path.join(outDir, `${id}.m4a`);
  if (!check) {
    // bitexact keeps the container free of encoder tags and timestamps, so a rebuild
    // from the same masters produces the same bytes and the same cache version.
    execFileSync(ffmpeg, ['-y', '-loglevel', 'error', '-i', wavPath, '-vn', '-c:a', 'aac', '-b:a', '96k', '-ar', '48000',
      '-map_metadata', '-1', '-fflags', '+bitexact', '-flags:a', '+bitexact', '-movflags', '+faststart', file]);
  }
  const encoded = await readFile(file);
  bank[id] = { url: `audio/${id}.m4a`, frames: info.frames, bytes: encoded.length,
    sha256: createHash('sha256').update(encoded).digest('hex'), masterSha256: info.masterSha256 };
}
const text = '// Generated by scripts/audio-bank.mjs from approved option A (+6 dB clicks).\n'
  + '// Original samples: Dustyroom and Chequered Ink. See assets/audio/maydan-casual/licenses/.\n'
  + '// The files live in public/audio (AAC 96 kb/s); sha256 covers the encoded file and\n'
  + '// masterSha256 the 24-bit PCM it was encoded from.\n'
  + `export const SAMPLE_RATE = 48000;\nexport const SAMPLE_BANK = ${JSON.stringify(bank, null, 2)};\n`;
if (check) {
  if (await readFile(target, 'utf8') !== text) throw new Error('Audio bank differs from the encoded files; run node scripts/audio-bank.mjs');
} else await writeFile(target, text, 'utf8');
const total = Object.values(bank).reduce((sum, entry) => sum + entry.bytes, 0);
console.log(`Audio bank: ${ids.length} approved cues, ${(total / 1024).toFixed(1)} KB of AAC in public/audio`);
