-- Moderation is fail-closed until an existing account ID is explicitly configured.
CREATE TABLE IF NOT EXISTS moderation_suspensions (user_id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, reason TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS moderation_image_reviews (seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('avatar','cover')), version TEXT NOT NULL, data_base64 TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, byte_length INTEGER NOT NULL, created_at INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','rejected')), reviewed_at INTEGER, reviewer_id TEXT, note TEXT, UNIQUE(user_id,kind));
CREATE INDEX IF NOT EXISTS moderation_images_status_seq ON moderation_image_reviews(status,seq);
CREATE TABLE IF NOT EXISTS moderation_image_approvals (user_id TEXT NOT NULL, kind TEXT NOT NULL, version TEXT NOT NULL, approved_at INTEGER NOT NULL, moderator_id TEXT NOT NULL, hidden_at INTEGER, reason TEXT, PRIMARY KEY(user_id,kind));
CREATE TABLE IF NOT EXISTS moderation_actions (seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, actor_id TEXT NOT NULL, client_id TEXT NOT NULL, request_hash TEXT NOT NULL, action TEXT NOT NULL, target_id TEXT NOT NULL, subject_user_id TEXT, reason TEXT NOT NULL, report_id TEXT, snapshot_json TEXT, created_at INTEGER NOT NULL, UNIQUE(actor_id,client_id));
CREATE TABLE IF NOT EXISTS moderation_report_decisions (report_id TEXT PRIMARY KEY, action_id TEXT NOT NULL, actor_id TEXT NOT NULL, reason TEXT NOT NULL, resolved_at INTEGER NOT NULL);
-- Quarantine pre-existing uploads without deleting or altering their bytes.
INSERT OR IGNORE INTO moderation_image_reviews(id,user_id,kind,version,data_base64,width,height,byte_length,created_at) SELECT 'legacy-' || i.user_id || '-' || i.kind,i.user_id,i.kind,i.version,i.data_base64,i.width,i.height,i.byte_length,i.updated_at FROM player_images i JOIN users u ON u.id=i.user_id WHERE NOT EXISTS(SELECT 1 FROM account_deletions d WHERE d.user_id=i.user_id) AND NOT EXISTS(SELECT 1 FROM moderation_image_approvals a WHERE a.user_id=i.user_id AND a.kind=i.kind AND a.version=i.version);
